# Generated by Django 4.1 on 2022-08-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=50)),
                ('model_car', models.CharField(max_length=50)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('body_type', models.CharField(blank=True, choices=[('sedan', 'Седан'), ('universal', 'Универсал'), ('kupe', 'Купе'), ('hetchbek', 'Хэтчбек'), ('miniven', 'Минивен'), ('jeep', 'Внедорожник'), ('pikap', 'Пикап')], max_length=100)),
            ],
        ),
    ]
