# Generated by Django 4.1 on 2022-08-09 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=50)),
                ('model_car', models.CharField(max_length=50)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('body_type', models.CharField(blank=True, choices=[('sedan', 'Седан'), ('universal', 'Универсал'), ('kupe', 'Купе'), ('hetchbek', 'Хэтчбек'), ('miniven', 'Минивен'), ('jeep', 'Внедорожник'), ('pikap', 'Пикап')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='auction.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
